[2024-06-24T11:40:38.157+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T11:40:38.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.processing_tasks.inject_data_kyiv scheduled__2024-06-22T00:00:00+00:00 [queued]>
[2024-06-24T11:40:38.214+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.processing_tasks.inject_data_kyiv scheduled__2024-06-22T00:00:00+00:00 [queued]>
[2024-06-24T11:40:38.215+0000] {taskinstance.py:2306} INFO - Starting attempt 9 of 9
[2024-06-24T11:40:38.243+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): processing_tasks.inject_data_kyiv> on 2024-06-22 00:00:00+00:00
[2024-06-24T11:40:38.254+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1744) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T11:40:38.257+0000] {standard_task_runner.py:63} INFO - Started process 1758 to run task
[2024-06-24T11:40:38.258+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'processing_tasks.inject_data_kyiv', 'scheduled__2024-06-22T00:00:00+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmprc6pixuv']
[2024-06-24T11:40:38.262+0000] {standard_task_runner.py:91} INFO - Job 179: Subtask processing_tasks.inject_data_kyiv
[2024-06-24T11:40:38.355+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.processing_tasks.inject_data_kyiv scheduled__2024-06-22T00:00:00+00:00 [running]> on host afc8096e8b86
[2024-06-24T11:40:38.646+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='processing_tasks.inject_data_kyiv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-22T00:00:00+00:00'
[2024-06-24T11:40:38.650+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T11:40:38.651+0000] {sql.py:276} INFO - Executing: 
            INSERT INTO public.measures (timestamp, temp, humidity, clouds, wind_speed, city)
            VALUES (to_timestamp(1719014400), 
                   289.55,
                   78,
                   81,
                   1.56,
                   'Kyiv'
            );
[2024-06-24T11:40:38.667+0000] {base.py:84} INFO - Using connection ID 'ps_db_conn' for task execution.
[2024-06-24T11:40:38.689+0000] {base.py:84} INFO - Using connection ID 'ps_db_conn' for task execution.
[2024-06-24T11:40:38.697+0000] {sql.py:487} INFO - Running statement: 
            INSERT INTO public.measures (timestamp, temp, humidity, clouds, wind_speed, city)
            VALUES (to_timestamp(1719014400), 
                   289.55,
                   78,
                   81,
                   1.56,
                   'Kyiv'
            );, parameters: None
[2024-06-24T11:40:38.699+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-24T11:40:38.703+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T11:40:38.722+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=processing_tasks.inject_data_kyiv, run_id=scheduled__2024-06-22T00:00:00+00:00, execution_date=20240622T000000, start_date=20240624T114038, end_date=20240624T114038
[2024-06-24T11:40:38.795+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-24T11:40:38.831+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T11:40:38.834+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
