[2024-06-24T11:08:23.775+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T11:08:23.798+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.processing_tasks.inject_data_kyiv scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-24T11:08:23.811+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.processing_tasks.inject_data_kyiv scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-24T11:08:23.811+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-06-24T11:08:23.831+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): processing_tasks.inject_data_kyiv> on 2024-06-23 00:00:00+00:00
[2024-06-24T11:08:23.840+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1095) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T11:08:23.841+0000] {standard_task_runner.py:63} INFO - Started process 1101 to run task
[2024-06-24T11:08:23.842+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'processing_tasks.inject_data_kyiv', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpxwgisdi8']
[2024-06-24T11:08:23.845+0000] {standard_task_runner.py:91} INFO - Job 118: Subtask processing_tasks.inject_data_kyiv
[2024-06-24T11:08:23.901+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.processing_tasks.inject_data_kyiv scheduled__2024-06-23T00:00:00+00:00 [running]> on host afc8096e8b86
[2024-06-24T11:08:24.075+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='processing_tasks.inject_data_kyiv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-23T00:00:00+00:00'
[2024-06-24T11:08:24.077+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T11:08:24.078+0000] {sql.py:276} INFO - Executing: 
            INSERT INTO public.measures (timestamp, temp, humidity, clouds, wind_speed, city)
            VALUES (to_timestamp(1719227341), 
                   293.9,
                   73,
                   81,
                   0.45,
                   'Kyiv'
            );
[2024-06-24T11:08:24.088+0000] {base.py:84} INFO - Using connection ID 'ps_db_conn' for task execution.
[2024-06-24T11:08:24.098+0000] {base.py:84} INFO - Using connection ID 'ps_db_conn' for task execution.
[2024-06-24T11:08:24.102+0000] {sql.py:487} INFO - Running statement: 
            INSERT INTO public.measures (timestamp, temp, humidity, clouds, wind_speed, city)
            VALUES (to_timestamp(1719227341), 
                   293.9,
                   73,
                   81,
                   0.45,
                   'Kyiv'
            );, parameters: None
[2024-06-24T11:08:24.103+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-24T11:08:24.105+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T11:08:24.115+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=processing_tasks.inject_data_kyiv, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20240624T110823, end_date=20240624T110824
[2024-06-24T11:08:24.136+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-24T11:08:24.159+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T11:08:24.162+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
