[2024-06-24T10:11:34.229+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T10:11:34.252+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.check_api scheduled__2024-06-22T00:00:00+00:00 [queued]>
[2024-06-24T10:11:34.265+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.check_api scheduled__2024-06-22T00:00:00+00:00 [queued]>
[2024-06-24T10:11:34.265+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-06-24T10:11:34.287+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): check_api> on 2024-06-22 00:00:00+00:00
[2024-06-24T10:11:34.297+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T10:11:34.299+0000] {standard_task_runner.py:63} INFO - Started process 74 to run task
[2024-06-24T10:11:34.299+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'check_api', 'scheduled__2024-06-22T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpmj1c5cra']
[2024-06-24T10:11:34.303+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask check_api
[2024-06-24T10:11:34.382+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.check_api scheduled__2024-06-22T00:00:00+00:00 [running]> on host afc8096e8b86
[2024-06-24T10:11:34.500+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='check_api' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-22T00:00:00+00:00'
[2024-06-24T10:11:34.502+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T10:11:34.502+0000] {baseoperator.py:400} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-06-24T10:11:34.502+0000] {http.py:137} INFO - Poking: data/2.5/weather
[2024-06-24T10:11:34.513+0000] {base.py:84} INFO - Using connection ID 'weather_conn' for task execution.
[2024-06-24T10:11:35.416+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-24T10:11:35.417+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T10:11:35.428+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=check_api, run_id=scheduled__2024-06-22T00:00:00+00:00, execution_date=20240622T000000, start_date=20240624T101134, end_date=20240624T101135
[2024-06-24T10:11:35.478+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-24T10:11:35.491+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
